apiVersion: "v1"
kind: "List"
metadata:
  name: "mongodb-secret-list"
items:
  - apiVersion: "v1"
    kind: "Secret"
    metadata:
      name: "mongodb-secret"
    type: "Opaque"
    data:
      database-admin-password: "bW9uZ29hZG1pbg=="
      database-name: "YWlybGluZQ=="
      database-password: "bW9uZ29hZG1pbg=="
      database-user: "bW9uZ29hZG1pbg=="
      keyfile-value: "cjNkaDR0Cg=="
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    name: "mongo"
  name: "mongo"
spec:
  ports:
    - port: 27017
      protocol: "TCP"
      targetPort: 27017
  selector:
    name: "mongo"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  labels:
    name: "mongo"
  name: "mongo"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    name: "mongo"
  name: "mongo"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "mongo"
  template:
    metadata:
      labels:
        name: "mongo"
    spec:
      containers:
        - image: "mongo:latest"
          name: "mongo"
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: "MONGODB_USER"
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mongodb-secret
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mongodb-secret
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-admin-password
                  name: mongodb-secret
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: mongodb-secret
            - name: MONGODB_KEYFILE_VALUE
              valueFrom:
                secretKeyRef:
                  key: keyfile-value
                  name: mongodb-secret
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WORKER_CLOUD_ID
              value: localhost
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
            - mountPath: /var/tmp/podinfo
              name: pod-info
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongo
        - name: pod-info
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
